import type { Metadata } from "next";
import "../style/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import localFont from "next/font/local";

const pretandard = localFont({
  src: "../public/fonts/PretendardGOVVariable.woff2",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={pretandard.className}>
      <body>{children}</body>
    </html>
  );
}
